import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 拆成两个 sidebar：
// - knowledgeSidebar 给 /docs/intro 等知识内容；
// - contributingSidebar 给 /docs/contributing/* 元规则。
// 用 category 节点显式包裹每个一级目录，让 _category_.json 的 generated-index
// 仍然生效（footer 与首页里的 /docs/category/xxx 链接依赖这些索引页）。
const sidebars: SidebarsConfig = {
  knowledgeSidebar: [
    'intro',
    {
      type: 'category',
      label: '课程笔记',
      link: {
        type: 'generated-index',
        slug: '/category/课程笔记',
        description: '微专业各门课程的通关攻略、实验避坑指南、推荐资源整理。',
      },
      items: [{type: 'autogenerated', dirName: 'courses'}],
    },
    {
      type: 'category',
      label: '比赛经验',
      link: {
        type: 'generated-index',
        slug: '/category/比赛经验',
        description: '智能车、电赛、RoboMaster、数模等赛事的技术栈、入坑指引与历届复盘。',
      },
      items: [{type: 'autogenerated', dirName: 'competitions'}],
    },
    {
      type: 'category',
      label: 'AI 工具链',
      link: {
        type: 'generated-index',
        slug: '/category/ai-工具链',
        description: 'AI Agent 使用心得、Prompt 库、本地大模型部署 SOP。',
      },
      items: [{type: 'autogenerated', dirName: 'ai-toolkit'}],
    },
    {
      type: 'category',
      label: '升学就业',
      link: {
        type: 'generated-index',
        slug: '/category/升学就业',
        description: '保研、考研、留学、就业的方向选择与经验合集。',
      },
      items: [{type: 'autogenerated', dirName: 'postgrad'}],
    },
    {
      type: 'category',
      label: '归档',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/category/归档',
        description: '已退役的内容，保留供历史追溯。',
      },
      items: [{type: 'autogenerated', dirName: 'archive'}],
    },
  ],

  contributingSidebar: [
    {type: 'autogenerated', dirName: 'contributing'},
  ],
};

export default sidebars;
